//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduTrack.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang_Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduTrack.Localization.Lang.Errors", typeof(Lang_Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такою Email уже зареєстровано у системі.
        /// </summary>
        public static string Authentication_DuplicateEmail {
            get {
                return ResourceManager.GetString("Authentication.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректний пароль користувача.
        /// </summary>
        public static string Authentication_InvalidPassword {
            get {
                return ResourceManager.GetString("Authentication.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний JWT Token.
        /// </summary>
        public static string Authentication_InvalidToken {
            get {
                return ResourceManager.GetString("Authentication.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термін дії RefreshToken-у закінчився.
        /// </summary>
        public static string Authentication_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Authentication.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курс неактивний. Зверніться до викладача.
        /// </summary>
        public static string Course_Inactive {
            get {
                return ResourceManager.GetString("Course.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відсутній навчальний курс.
        /// </summary>
        public static string Course_NotFound {
            get {
                return ResourceManager.GetString("Course.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент/ка з такою адресою елетронної пошти уже додано на курс.
        /// </summary>
        public static string Course_StudentExists {
            get {
                return ResourceManager.GetString("Course.StudentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У підгрупі присутні студенти.
        /// </summary>
        public static string Course_Subgroup_HasStudents {
            get {
                return ResourceManager.GetString("Course.Subgroup.HasStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрошення деактивовано викладачем.
        /// </summary>
        public static string Invite_Deactivated {
            get {
                return ResourceManager.GetString("Invite.Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термін дії запрошення закінчився. Отримайте нове запрошення у викладача.
        /// </summary>
        public static string Invite_Expired {
            get {
                return ResourceManager.GetString("Invite.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на запрошення недійсне або видалене викладачем.
        /// </summary>
        public static string Invite_NotFound {
            get {
                return ResourceManager.GetString("Invite.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення для параметра {0} відсутнє. Перевірте налаштування.
        /// </summary>
        public static string Option_EmptyValue {
            get {
                return ResourceManager.GetString("Option.EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметер {0} відсутній. Перевірте налаштування.
        /// </summary>
        public static string Option_NotFound {
            get {
                return ResourceManager.GetString("Option.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обліковий запис користувача не активовано, завершіть реєстрацію.
        /// </summary>
        public static string User_NotApproved {
            get {
                return ResourceManager.GetString("User.NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з такими обліковими даними відсутній.
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не знайдено у системі.
        /// </summary>
        public static string UserRole_NotFound {
            get {
                return ResourceManager.GetString("UserRole.NotFound", resourceCulture);
            }
        }
    }
}
